entities:
  3M: MMM
  A. O. Smith: AOS
  Abbott Laboratories: ABT
  AbbVie: ABBV
  Accenture: ACN
  Adobe Inc.: ADBE
  Adobe: ADBE
  Advanced Micro Devices: AMD
  AES Corporation: AES
  Aflac: AFL
  Agilent Technologies: A
  Air Products: APD
  Airbnb: ABNB
  Akamai Technologies: AKAM
  Albemarle Corporation: ALB
  Alexandria Real Estate Equities: ARE
  Align Technology: ALGN
  Allegion: ALLE
  Alliant Energy: LNT
  Allstate: ALL
  Alphabet Inc. (Class A): GOOGL
  Alphabet: GOOG
  Alphabet Inc. (Class C): GOOG
  Altria: MO
  Amazon: AMZN
  Amcor: AMCR
  Ameren: AEE
  American Electric Power: AEP
  American Express: AXP
  American International Group: AIG
  American Tower: AMT
  American Water Works: AWK
  Ameriprise Financial: AMP
  Ametek: AME
  Amgen: AMGN
  Amphenol: APH
  Analog Devices: ADI
  Aon plc: AON
  Aon: AON
  APA Corporation: APA
  Apollo Global Management: APO
  Apple Inc.: AAPL
  Apple: AAPL
  Applied Materials: AMAT
  AppLovin: APP
  Aptiv: APTV
  Arch Capital Group: ACGL
  Archer Daniels Midland: ADM
  Ares Management: ARES
  Arista Networks: ANET
  Arthur J. Gallagher & Co.: AJG
  Arthur J. Gallagher &: AJG
  Assurant: AIZ
  AT&T: T
  Atmos Energy: ATO
  Autodesk: ADSK
  Automatic Data Processing: ADP
  AutoZone: AZO
  AvalonBay Communities: AVB
  Avery Dennison: AVY
  Axon Enterprise: AXON
  Baker Hughes: BKR
  Ball Corporation: BALL
  Bank of America: BAC
  Baxter International: BAX
  Becton Dickinson: BDX
  Berkshire Hathaway: BRK-B
  Best Buy: BBY
  Bio-Techne: TECH
  Biogen: BIIB
  BlackRock: BLK
  Blackstone Inc.: BX
  Blackstone: BX
  Block, Inc.: XYZ
  Block,: XYZ
  BNY Mellon: BK
  Boeing: BA
  Booking Holdings: BKNG
  Boston Scientific: BSX
  Bristol Myers Squibb: BMY
  Broadcom: AVGO
  Broadridge Financial Solutions: BR
  Brown & Brown: BRO
  Brown–Forman: BF-B
  Builders FirstSource: BLDR
  Bunge Global: BG
  BXP, Inc.: BXP
  BXP,: BXP
  C.H. Robinson: CHRW
  Cadence Design Systems: CDNS
  Camden Property Trust: CPT
  Campbell's Company (The): CPB
  Campbell's: CPB
  Capital One: COF
  Cardinal Health: CAH
  Carnival: CCL
  Carrier Global: CARR
  Carvana: CVNA
  Caterpillar Inc.: CAT
  Caterpillar: CAT
  Cboe Global Markets: CBOE
  CBRE Group: CBRE
  CDW Corporation: CDW
  Cencora: COR
  Centene Corporation: CNC
  CenterPoint Energy: CNP
  CF Industries: CF
  Charles River Laboratories: CRL
  Charles Schwab Corporation: SCHW
  Charter Communications: CHTR
  Chevron Corporation: CVX
  Chipotle Mexican Grill: CMG
  Chubb Limited: CB
  Church & Dwight: CHD
  Cigna: CI
  Cincinnati Financial: CINF
  Cintas: CTAS
  Cisco: CSCO
  Citigroup: C
  Citizens Financial Group: CFG
  Clorox: CLX
  CME Group: CME
  CMS Energy: CMS
  Coca-Cola Company (The): KO
  Coca-Cola: KO
  Cognizant: CTSH
  Coinbase: COIN
  Colgate-Palmolive: CL
  Comcast: CMCSA
  Comfort Systems USA: FIX
  Conagra Brands: CAG
  ConocoPhillips: COP
  Consolidated Edison: ED
  Constellation Brands: STZ
  Constellation Energy: CEG
  Cooper Companies (The): COO
  Copart: CPRT
  Corning Inc.: GLW
  Corning: GLW
  Corpay: CPAY
  Corteva: CTVA
  CoStar Group: CSGP
  Costco: COST
  Coterra: CTRA
  CRH plc: CRH
  CRH: CRH
  CrowdStrike: CRWD
  Crown Castle: CCI
  CSX Corporation: CSX
  Cummins: CMI
  CVS Health: CVS
  Danaher Corporation: DHR
  Darden Restaurants: DRI
  Datadog: DDOG
  DaVita: DVA
  Dayforce: DAY
  Deckers Brands: DECK
  Deere & Company: DE
  Deere &: DE
  Dell Technologies: DELL
  Delta Air Lines: DAL
  Devon Energy: DVN
  Dexcom: DXCM
  Diamondback Energy: FANG
  Digital Realty: DLR
  Dollar General: DG
  Dollar Tree: DLTR
  Dominion Energy: D
  Domino's: DPZ
  DoorDash: DASH
  Dover Corporation: DOV
  Dow Inc.: DOW
  Dow: DOW
  D. R. Horton: DHI
  DTE Energy: DTE
  Duke Energy: DUK
  DuPont: DD
  Eaton Corporation: ETN
  eBay Inc.: EBAY
  eBay: EBAY
  Ecolab: ECL
  Edison International: EIX
  Edwards Lifesciences: EW
  Electronic Arts: EA
  Elevance Health: ELV
  Emcor: EME
  Emerson Electric: EMR
  Entergy: ETR
  EOG Resources: EOG
  EPAM Systems: EPAM
  EQT Corporation: EQT
  Equifax: EFX
  Equinix: EQIX
  Equity Residential: EQR
  Erie Indemnity: ERIE
  Essex Property Trust: ESS
  Estée Lauder Companies (The): EL
  Everest Group: EG
  Evergy: EVRG
  Eversource Energy: ES
  Exelon: EXC
  Expand Energy: EXE
  Expedia Group: EXPE
  Expeditors International: EXPD
  Extra Space Storage: EXR
  ExxonMobil: XOM
  F5, Inc.: FFIV
  F5,: FFIV
  FactSet: FDS
  Fair Isaac: FICO
  Fastenal: FAST
  Federal Realty Investment Trust: FRT
  FedEx: FDX
  Fidelity National Information Services: FIS
  Fifth Third Bancorp: FITB
  First Solar: FSLR
  FirstEnergy: FE
  Fiserv: FISV
  Ford Motor Company: F
  Ford Motor: F
  Fortinet: FTNT
  Fortive: FTV
  Fox Corporation (Class A): FOXA
  Fox Corporation (Class B): FOX
  Franklin Resources: BEN
  Freeport-McMoRan: FCX
  Garmin: GRMN
  Gartner: IT
  GE Aerospace: GE
  GE HealthCare: GEHC
  GE Vernova: GEV
  Gen Digital: GEN
  Generac: GNRC
  General Dynamics: GD
  General Mills: GIS
  General Motors: GM
  Genuine Parts Company: GPC
  Genuine Parts: GPC
  Gilead Sciences: GILD
  Global Payments: GPN
  Globe Life: GL
  GoDaddy: GDDY
  Goldman Sachs: GS
  Halliburton: HAL
  Hartford (The): HIG
  Hasbro: HAS
  HCA Healthcare: HCA
  Healthpeak Properties: DOC
  Henry Schein: HSIC
  Hershey Company (The): HSY
  Hershey: HSY
  Hewlett Packard Enterprise: HPE
  Hilton Worldwide: HLT
  Hologic: HOLX
  Home Depot (The): HD
  Honeywell: HON
  Hormel Foods: HRL
  Host Hotels & Resorts: HST
  Howmet Aerospace: HWM
  HP Inc.: HPQ
  HP: HPQ
  Hubbell Incorporated: HUBB
  Humana: HUM
  Huntington Bancshares: HBAN
  Huntington Ingalls Industries: HII
  IBM: IBM
  IDEX Corporation: IEX
  Idexx Laboratories: IDXX
  Illinois Tool Works: ITW
  Incyte: INCY
  Ingersoll Rand: IR
  Insulet Corporation: PODD
  Intel: INTC
  Interactive Brokers: IBKR
  Intercontinental Exchange: ICE
  International Flavors & Fragrances: IFF
  International Paper: IP
  Intuit: INTU
  Intuitive Surgical: ISRG
  Invesco: IVZ
  Invitation Homes: INVH
  IQVIA: IQV
  Iron Mountain: IRM
  J.B. Hunt: JBHT
  Jabil: JBL
  Jack Henry & Associates: JKHY
  Jacobs Solutions: J
  Johnson & Johnson: JNJ
  Johnson Controls: JCI
  JPMorgan Chase: JPM
  Kenvue: KVUE
  Keurig Dr Pepper: KDP
  KeyCorp: KEY
  Keysight Technologies: KEYS
  Kimberly-Clark: KMB
  Kimco Realty: KIM
  Kinder Morgan: KMI
  KKR & Co.: KKR
  KKR &: KKR
  KLA Corporation: KLAC
  Kraft Heinz: KHC
  Kroger: KR
  L3Harris: LHX
  Labcorp: LH
  Lam Research: LRCX
  Lamb Weston: LW
  Las Vegas Sands: LVS
  Leidos: LDOS
  Lennar: LEN
  Lennox International: LII
  Lilly (Eli): LLY
  Linde plc: LIN
  Linde: LIN
  Live Nation Entertainment: LYV
  Lockheed Martin: LMT
  Loews Corporation: L
  Lowe's: LOW
  Lululemon Athletica: LULU
  LyondellBasell: LYB
  M&T Bank: MTB
  Marathon Petroleum: MPC
  Marriott International: MAR
  Marsh McLennan: MRSH
  Martin Marietta Materials: MLM
  Masco: MAS
  Mastercard: MA
  Match Group: MTCH
  McCormick & Company: MKC
  McCormick &: MKC
  McDonald's: MCD
  McKesson Corporation: MCK
  Medtronic: MDT
  Merck & Co.: MRK
  Merck &: MRK
  Meta Platforms: META
  MetLife: MET
  Mettler Toledo: MTD
  MGM Resorts: MGM
  Microchip Technology: MCHP
  Micron Technology: MU
  Microsoft: MSFT
  Mid-America Apartment Communities: MAA
  Moderna: MRNA
  Molina Healthcare: MOH
  Molson Coors Beverage Company: TAP
  Molson Coors Beverage: TAP
  Mondelez International: MDLZ
  Monolithic Power Systems: MPWR
  Monster Beverage: MNST
  Moody's Corporation: MCO
  Morgan Stanley: MS
  Mosaic Company (The): MOS
  Mosaic: MOS
  Motorola Solutions: MSI
  MSCI Inc.: MSCI
  MSCI: MSCI
  Nasdaq, Inc.: NDAQ
  Nasdaq,: NDAQ
  NetApp: NTAP
  Netflix: NFLX
  Newmont: NEM
  News Corp (Class A): NWSA
  News Corp (Class B): NWS
  NextEra Energy: NEE
  Nike, Inc.: NKE
  Nike,: NKE
  NiSource: NI
  Nordson Corporation: NDSN
  Norfolk Southern: NSC
  Northern Trust: NTRS
  Northrop Grumman: NOC
  Norwegian Cruise Line Holdings: NCLH
  NRG Energy: NRG
  Nucor: NUE
  Nvidia: NVDA
  NVR, Inc.: NVR
  NVR,: NVR
  NXP Semiconductors: NXPI
  O’Reilly Automotive: ORLY
  Occidental Petroleum: OXY
  Old Dominion: ODFL
  Omnicom Group: OMC
  ON Semiconductor: 'ON'
  Oneok: OKE
  Oracle Corporation: ORCL
  Otis Worldwide: OTIS
  Paccar: PCAR
  Packaging Corporation of America: PKG
  Palantir Technologies: PLTR
  Palo Alto Networks: PANW
  Paramount Skydance Corporation: PSKY
  Parker Hannifin: PH
  Paychex: PAYX
  Paycom: PAYC
  PayPal: PYPL
  Pentair: PNR
  PepsiCo: PEP
  Pfizer: PFE
  PG&E Corporation: PCG
  Philip Morris International: PM
  Phillips 66: PSX
  Pinnacle West Capital: PNW
  PNC Financial Services: PNC
  Pool Corporation: POOL
  PPG Industries: PPG
  PPL Corporation: PPL
  Principal Financial Group: PFG
  Procter & Gamble: PG
  Progressive Corporation: PGR
  Prologis: PLD
  Prudential Financial: PRU
  Public Service Enterprise Group: PEG
  PTC Inc.: PTC
  PTC: PTC
  Public Storage: PSA
  PulteGroup: PHM
  Quanta Services: PWR
  Qualcomm: QCOM
  Quest Diagnostics: DGX
  Qnity Electronics: Q
  Ralph Lauren Corporation: RL
  Raymond James Financial: RJF
  RTX Corporation: RTX
  Realty Income: O
  Regency Centers: REG
  Regeneron Pharmaceuticals: REGN
  Regions Financial Corporation: RF
  Republic Services: RSG
  ResMed: RMD
  Revvity: RVTY
  Robinhood Markets: HOOD
  Rockwell Automation: ROK
  Rollins, Inc.: ROL
  Rollins,: ROL
  Roper Technologies: ROP
  Ross Stores: ROST
  Royal Caribbean Group: RCL
  S&P Global: SPGI
  Salesforce: CRM
  Sandisk: SNDK
  SBA Communications: SBAC
  Schlumberger: SLB
  Seagate Technology: STX
  Sempra: SRE
  ServiceNow: NOW
  Sherwin-Williams: SHW
  Simon Property Group: SPG
  Skyworks Solutions: SWKS
  J.M. Smucker Company (The): SJM
  J.M. Smucker: SJM
  Smurfit Westrock: SW
  Snap-on: SNA
  Solventum: SOLV
  Southern Company: SO
  Southern: SO
  Southwest Airlines: LUV
  Stanley Black & Decker: SWK
  Starbucks: SBUX
  State Street Corporation: STT
  Steel Dynamics: STLD
  Steris: STE
  Stryker Corporation: SYK
  Supermicro: SMCI
  Synchrony Financial: SYF
  Synopsys: SNPS
  Sysco: SYY
  T-Mobile US: TMUS
  T. Rowe Price: TROW
  Take-Two Interactive: TTWO
  Tapestry, Inc.: TPR
  Tapestry,: TPR
  Targa Resources: TRGP
  Target Corporation: TGT
  TE Connectivity: TEL
  Teledyne Technologies: TDY
  Teradyne: TER
  Tesla, Inc.: TSLA
  Tesla,: TSLA
  Texas Instruments: TXN
  Texas Pacific Land Corporation: TPL
  Textron: TXT
  Thermo Fisher Scientific: TMO
  TJX Companies: TJX
  TKO Group Holdings: TKO
  Trade Desk (The): TTD
  Tractor Supply: TSCO
  Trane Technologies: TT
  TransDigm Group: TDG
  Travelers Companies (The): TRV
  Trimble Inc.: TRMB
  Trimble: TRMB
  Truist Financial: TFC
  Tyler Technologies: TYL
  Tyson Foods: TSN
  U.S. Bancorp: USB
  Uber: UBER
  UDR, Inc.: UDR
  UDR,: UDR
  Ulta Beauty: ULTA
  Union Pacific Corporation: UNP
  United Airlines Holdings: UAL
  United Parcel Service: UPS
  United Rentals: URI
  UnitedHealth Group: UNH
  Universal Health Services: UHS
  Valero Energy: VLO
  Ventas: VTR
  Veralto: VLTO
  Verisign: VRSN
  Verisk Analytics: VRSK
  Verizon: VZ
  Vertex Pharmaceuticals: VRTX
  Viatris: VTRS
  Vici Properties: VICI
  Visa Inc.: V
  Visa: V
  Vistra Corp.: VST
  Vistra: VST
  Vulcan Materials Company: VMC
  Vulcan Materials: VMC
  W. R. Berkley Corporation: WRB
  W. W. Grainger: GWW
  Wabtec: WAB
  Walmart: WMT
  Walt Disney Company (The): DIS
  Walt Disney: DIS
  Warner Bros. Discovery: WBD
  Waste Management: WM
  Waters Corporation: WAT
  WEC Energy Group: WEC
  Wells Fargo: WFC
  Welltower: WELL
  West Pharmaceutical Services: WST
  Western Digital: WDC
  Weyerhaeuser: WY
  Williams-Sonoma, Inc.: WSM
  Williams-Sonoma,: WSM
  Williams Companies: WMB
  Willis Towers Watson: WTW
  Workday, Inc.: WDAY
  Workday,: WDAY
  Wynn Resorts: WYNN
  Xcel Energy: XEL
  Xylem Inc.: XYL
  Xylem: XYL
  Yum! Brands: YUM
  Zebra Technologies: ZBRA
  Zimmer Biomet: ZBH
  Zoetis: ZTS
